#
# Default Config.
#
Config_Version: 0

#
# The tag that the plugin will show with commands.
#
Plugin_Tag: '&f&l[&9BDN&f&l]&r '

#
# Permissions.
#
Need_Permissions: True
Ops_Need_Permissions: False

#
# Whitelist Servers.
#
Whitelist_On: false
Whitelisted_Servers:
  - 'Server'
  - 'Names'
  - 'Here'

#
# Nicknames.
#
Use_Prefix: True
Prefix: '&9+'
Length_Limit: True
Length: 25
Use_Colors: True

#
# Other.
#