#  ______               _
# |___  /              | |
#    / / __ _ _ __ ___ | |__   ___  ___  ___   ___
#   / / / _` | '_ ` _ \| '_ \ / _ \/ __|/ _ \ / _ \
#  / /_| (_| | | | | | | |_) | (_) \__ \ (_) |  __/
# /_____\__,_|_| |_| |_|_.__/ \___/|___/\___/ \___|
Plugin:
  Plugin_Tag: '&f&l[&9BDN&f&l]&9 '
  Allowed_Servers:
  - servernamehere
  - justaddanother
  Limit_Name_Length:
    Count_Spaces: true
    Count_&: false
    Max: 25