#  ______               _
# |___  /              | |
#    / / __ _ _ __ ___ | |__   ___  ___  ___   ___
#   / / / _` | '_ ` _ \| '_ \ / _ \/ __|/ _ \ / _ \
#  / /_| (_| | | | | | | |_) | (_) \__ \ (_) |  __/
# /_____\__,_|_| |_| |_|_.__/ \___/|___/\___/ \___|
name: BungeeDisplayName
main: to.us.zambosoe.bdn.Main
version: 2.0.0
author: Zambosoe